= Introduction
include::_attributes.adoc[]

This lab provides instructions for running the OpenShift Service Mesh and 3scale API Management Integration demo.

Audience: API Owner, Product Manager, Developers, Architects

[#Overview]
== Overview
In a Micro Services Architecture (MSA), there are different stakeholders for API Management and Service Mesh capabilities. Service Mesh provides observability, traceability, security and control to application develops and dev-ops engineers to monitor intra-service communications.

API management provides API providers and business owners ability to provide business API capabilities like security, rate limiting, billing and developer ecosystem.

This link:https://www.redhat.com/rhdc/managed-files/cl-service-mesh-and-api-management-e-book-f28474-202104-en.pdf[eBook, window="_blank"] from Red Hat is a good foundation for understanding the interplay between Service Mesh and API Management in a MSA.

[#installation]
== Installation Steps
You are provided with an *OpenShift Container Platform 4.9* environment and will perform all the below actions as a part of this lab

. Installing 3scale
. Installing OpenShift Service Mesh
. Configuring Service Mesh
. Provisioning the BookInfo product (microservices) behind Istio gateway
. Configuring 3scale
. Enabling API Management

Click xref:01-path1.adoc[here] to get started
